version: '3.5'
services:
  backend:
    image: kanutan93/msa-homework:1.4.4
    environment:
      DB_URL: 'jdbc:postgresql://db:5432/test'
      DB_USER: 'test_user'
      DB_PASSWORD: 'password'
    ports:
      - "8080:8080"

  db:
    container_name:  db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'password'
    volumes:
        - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg: