spring:
  application:
    name: homework3
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/test}
    username: ${DB_USER:test_user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

management:
  metrics:
    web:
      server:
        request:
          autotime:
            percentiles: 1, 0.99, 0.95, 0.5
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
