{
 "title": "SpringBoot APM Dashboard",
 "description": "Dashboard for Spring Boot Metrics",
 "time": { "from": "2023-07-04T18:30:46.632Z", "to": "2023-07-04T18:40:46.632Z" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Database statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit[5m])",
     "legendFormat": "{{datname}} commits"
    }
   ]
  },
  {
   "title": "Update data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_updated[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Fetch data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_fetched[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Delete data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_tup_deleted[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Pod resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{pod=~\"homework3-dep.*\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{pod=~\"homework3-dep.*\"} / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HTTP Statistics by nginx_ingress_controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests[2m])), 0.001)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le, ingress))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le, ingress))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m])) by (le, ingress))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"$application\", instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_cpu_usage{instance=~\"$instance\", application=\"$application\"})",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "avg(process_cpu_usage{instance=~\"$instance\", application=\"$application\"})",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(system_load_average_1m{instance=~\"$instance\", application=\"$application\"})",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "avg(system_cpu_count{instance=~\"$instance\", application=\"$application\"})",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "Connection pool Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics by API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(http_server_requests_seconds_count{instance=~\"$instance\", uri!~\".*actuator.*\", status=\"500\"}) / sum(http_server_requests_seconds_count{instance=~\"$instance\", uri!~\".*actuator.*\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])) by (method, uri)",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Latency POST - /user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p99 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p95 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p50 {{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Latency GET - /user/{userId}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p99 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p95 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p50 {{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Latency DELETE - /user/{userId}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p99 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p95 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p50 {{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Latency PUT - /user/{userId}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p99 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p95 {{method}} - {{uri}}"
    },
    {
     "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
     "legendFormat": "p50 {{method}} - {{uri}}"
    }
   ]
  }
 ]
}