{
 "title": "SpringBoot APM Dashboard",
 "description": "Dashboard for Spring Boot Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Statistics by nginx_ingress_controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 8, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "options": { "reduceOptions": { "calcs": [ "first" ] } },
     "targets": [
      {
       "expr": "avg(process_start_time_seconds{application=\"$application\", instance=~\"$instance\"})*1000"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(system_cpu_usage{instance=~\"$instance\", application=\"$application\"})",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "avg(process_cpu_usage{instance=~\"$instance\", application=\"$application\"})",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(system_load_average_1m{instance=~\"$instance\", application=\"$application\"})",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "avg(system_cpu_count{instance=~\"$instance\", application=\"$application\"})",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection pool Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=~\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics by API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Error rate",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "error_rate_counter_total{instance=~\"$instance\", uri!~\".*actuator.*\"}",
       "legendFormat": "{{method}} - {{uri}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])) by (method, uri)",
       "legendFormat": "{{method}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Latency POST - /user",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p99 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p95 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"POST\", uri=\"/user\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p50 {{method}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Latency GET - /user/{userId}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p99 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p95 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"GET\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p50 {{method}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Latency DELETE - /user/{userId}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p99 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p95 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"DELETE\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p50 {{method}} - {{uri}}"
      }
     ]
    },
    {
     "title": "Latency PUT - /user/{userId}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "quantile(0.99,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p99 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.95,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p95 {{method}} - {{uri}}"
      },
      {
       "expr": "quantile(0.5,\r\n    irate(http_server_requests_seconds_sum{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m]) \r\n    / irate(http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\", method = \"PUT\", uri=\"/user/{userId}\"}[5m])\r\n) by (method, uri)",
       "legendFormat": "p50 {{method}} - {{uri}}"
      }
     ]
    }
   ]
  }
 ]
}