{{- if .Values.app.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
    {{- range $key, $value := .Values.app.secret }}
     - {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}