apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
    DB_URL: jdbc:postgresql://{{ .Values.app.name }}-db:5432/{{ .Values.app.name }}
    DB_NAME: {{ .Values.app.name }}
    DB_USER: postgres
    DB_PASSWORD: password
